# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "Inxton.*"
    automerged_updates:
      - match:
          dependency_name: "Inxton.*"
